# Generated by Django 3.1.2 on 2020-11-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20201101_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Movie_rate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('movie_id', models.IntegerField()),
                ('rate', models.IntegerField(default=0)),
            ],
        ),
    ]
