# Generated by Django 3.1.2 on 2020-11-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_user_movie_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_movie_rate',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
