# Generated by Django 3.1.2 on 2020-11-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_user_movie_rate_integer_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='movie_name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
