# Generated by Django 3.1.2 on 2020-11-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_wishlist_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_image',
            field=models.FileField(default='movie_image/default.jpg', upload_to='movie_image/'),
        ),
    ]
