# Generated by Django 3.1.2 on 2020-11-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_movie_movie_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('movie_id', models.IntegerField()),
                ('view_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
